version: '3.7'
services:
    nginx:
        image: nginx:1.19-alpine
        ports:
            - 80:80
        volumes:
            - ".:/var/www/phpversions"
            - ".docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
        working_dir: /var/www/phpversions

    fpm:
        build: .docker
        environment:
            - APP_ENV=prod
            - DATABASE_DSN=sqlite:/var/www/phpversions/var/db.sqlite
        volumes:
            - ".:/var/www/phpversions"
        working_dir: /var/www/phpversions
